---
  host: "{{ ansible_host }}"
  username: cisco
  password: cisco
  vpc:
    domain: 12
    pkl_dest: 192.168.255.9
    pkl_src: 192.168.255.10
    pkl_vrf: vpc-mgt
    role_priority: 32667
  l3_interfaces:
    - interface_type: Ethernet
      interface_id: 1/1
      description: VPC Keepalive Link
      ip_address: 192.168.255.10
      subnet_mask: 255.255.255.252
      prefix: 30
  l2_interfaces:
      - interface_type: Port-Channel
        interface_id: 1
        mode: trunk
        description: VPC Peer Link